### PR TITLE
Adding support for esp32s3, fixing some compile errors

### PR DESCRIPTION
**Pull request by cr1tbit**
Hey, I'm really grateful for this project, will speed up my work considerably.

Sharing my fixes allowing it to run with ESP32S3.

Best regards,
Jakub

### CODE REVIEW

**Comment by NoahMaceri** [comment]
Just wanted to comment and confirm that this update is working on an ESP32s3. Might want to update the Kconfig.projbuild with defaults for the s3 (Will have the change range from 0 to 47).
The pins I used to test:
- MOSI_GPIO 35 (SPII06)
- SCLK_GPIO 47 (SPICLK_P)
- CS_GPIO 36 (SPII07)
- DC_GPIO 4
- RESET_GPIO 5
- BL_GPIO 6

**Comment by nopnop2002** [comment]
Thank you for PR.

I ordered the ESP32-S3.

I will refer to your PR.

**Comment by nopnop2002** [comment]
Currently, ESP-IDF is in the process of migrating to Ver5.

S3 support and Ver5 support should be considered separately.

These are mixed in your PR.

ESP-IDF Ver5 is very buggy.

The transition to Ver5 is very dangerous.

Therefore, I will support ESP32-S3 with Ver4.4 in the near future.

When ESP-IDF Ver5 becomes stable, we will release the corresponding version again.

**Comment by cr1tbit** [comment]
All right, I'm not (yet) that deeply into ESP32 development to know such things.

I suggest leaving that PR open until you make those changes, since it helped at least one person so far.

Thanks for looking into my contribution :)

**Comment by nopnop2002** [comment]
Unlike esp32-s2, esp32-s3 can use the JPEG library.

```
$ ls esp-idf/components/esp_rom/include/esp32s3/rom/tjpgd.h
esp-idf/components/esp_rom/include/esp32s3/rom/tjpgd.h
```

**Comment by nopnop2002** [comment]
When I enabled the touch panel on ESP32S3, I found that there was a limit to the GPIOs that could be used.

As a result of many experiments, I found a pin assignment that works on the touch panel.

**Comment by nopnop2002** [comment]
The changes to Kconfig.projbuild have already been implemented in the latest version.

**Pull request closed without merging**
