### PR TITLE
Convert to component

### PR DESCRIPTION
**Pull request by camielverdult**

### CODE REVIEW

**Comment by nopnop2002** [comment]
I checked the contents of your PR and found that it is not configured as a component.

Click here to learn how to create components.

https://github.com/nopnop2002/esp-idf-parallel-tft

I can convert this project into components at any time.

**Comment by camielverdult** [comment]
>I can immediately convert this project into components.

Could you do that?

**Comment by nopnop2002** [comment]
Let's do it next weekend

**Comment by nopnop2002** [comment]
i did it

**Comment by camielverdult** [comment]
Great! Thanks :)

Have you thought about including your project into esp-idf-lib? It might gain some additional traction there.

**Comment by nopnop2002** [comment]
esp-idf-lib is a repository owned by UncleRus and has nothing to do with me.

**Pull request closed without merging**
